# === GIT ALIASES ===
alias g='git'
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias gp='git push'
alias gl='git pull'
alias gco='git checkout'
alias gd='git diff'
alias gb='git branch'
alias glog='git log --oneline --graph --decorate'

# === DOCKER ALIASES ===
alias d='docker'
alias dps='docker ps'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias dexec='docker exec -it'
alias dimg='docker images'
alias drm='docker rm -f'
alias drmi='docker rmi'
alias dbash='docker exec -it $(docker ps -q | head -n1) bash'

# === KUBERNETES ALIASES ===
alias k='kubectl'
alias kgp='kubectl get pods'
alias kgs='kubectl get svc'
alias kgn='kubectl get nodes'
alias kctx='kubectl config use-context'
alias kctxs='kubectl config get-contexts'
alias klog='kubectl logs'
alias kexec='kubectl exec -it'
alias kdes='kubectl describe'

# === TERRAFORM ALIASES ===
alias tf='terraform'
alias tfi='terraform init'
alias tfp='terraform plan'
alias tfa='terraform apply'
alias tfd='terraform destroy'
alias tfo='terraform output'

# === UTILITY SHORTCUTS ===
alias c='clear'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ..='cd ..'
alias ...='cd ../..'
